### ISSUE TITLE
Update README.md 💣

### ISSUE THREAD

**Issue by durul** [Jaennaet/pISSStream#8]
Please update README.md files with iPhone Vision Pro images and details.😎

**Comment by Jaennaet** [comment]
Oh yeah, and need to add that contributor section too!

You know the ins-and-outs of the Vision stuff much better since I don't really have a way of testing it out. I can definitely do the README update but maybe you could give me a quick description of what's currently supported?

Hmm, is the release situation on visionOS the same as iOS, ie. that it's hard to run something that's not from the App Store? Maybe adding building & installation instructions for iOS & visionOS (if needed) might be a good idea, since I guess we have no sane way of distributing binaries for them (TestFlight doesn't really count 😀)

**Comment by durul** [comment]
I created a new PR with building & installation instructions for iOS & visionOS.
